window.samples = [{ id: 1, icon: "ion-sync-accordion", control: "Accordion", name: "Accordion" },
          { id: 2, icon: "ion-sync-autocomplete", control: "AutoComplete", name: "Autocomplete" },
          { id: 3,  icon: "ion-sync-barcode", control: "Barcode", name: "Barcode" },
          { id: 4,  icon: "ion-sync-bulletgraph", control: "Bullet Graph", name: "BulletGraph" },
          { id: 5,  icon: "ion-sync-button", control: "Button", name: "Button" },
          { id: 6,  icon: "ion-sync-chart", control: "Chart", name: "Chart" },
          { id: 7,  icon: "ion-sync-circulargauge", control: "Circular Gauge", name: "CircularGauge" },
		  { id: 8,  icon: "ion-sync-dropdownlist", control: "ComboBox", name: "ComboBox" },
          { id: 8,  icon: "ion-sync-colorpicker", control: "ColorPicker", name: "ColorPicker" },
          { id: 9,  icon: "ion-sync-datepicker", control: "DatePicker", name: "DatePicker" },
          { id: 10, icon: "ion-sync-datetimepicker", control: "DateTimePicker", name: "DateTimePicker" },
          { id: 58,  icon: "ion-sync-daterangepicker", control: "DateRangePicker", name: "DateRangePicker" },
          { id: 11,  icon: "ion-sync-diagram", control: "Diagram", name: "Diagram" },
          { id: 12,  icon: "ion-sync-dialog", control: "Dialog", name: "Dialog" },
          { id: 13,  icon: "ion-sync-digitalgauge", control: "Digital Gauge", name: "DigitalGauge" },
          { id: 14,  icon: "ion-sync-dropdownlist", control: "DropDownList", name: "DropDownList" },
          { id: 15,  icon: "ion-sync-fileexplorer", control: "FileExplorer", name: "FileExplorer" },
          { id: 16,  icon: "ion-sync-grid", control: "Grid", name: "Grid" },
          { id: 17,  icon: "ion-sync-heatmap", control: "HeatMap", name: "HeatMap" },
          { id: 18,  icon: "ion-sync-kanbanboard", control: "KanbanBoard", name: "KanbanBoard" },
          { id: 19,  icon: "ion-sync-lineargauge", control: "Linear Gauge", name: "LinearGauge" },
          { id: 20,  icon: "ion-sync-listbox", control: "ListBox", name: "ListBox" },
          { id: 21,  icon: "ion-sync-listview", control: "ListView", name: "ListView" },
          { id: 22,  icon: "ion-sync-maps", control: "Maps", name: "Maps" },
          { id: 23,  icon: "ion-sync-menu", control: "Menu", name: "Menu" },
          { id: 24,  icon: "ion-sync-navigationdrawer", control: "NavigationDrawer", name: "NavigationDrawer" },
          { id: 25,  icon: "ion-sync-pdfviewer", control: "PDF Viewer", name: "PDF Viewer" },
          { id: 26,  icon: "ion-sync-pivotchart", control: "PivotChart", name: "PivotChart" },
          { id: 27,  icon: "ion-sync-pivotgauge", control: "PivotGauge", name: "PivotGauge" },
          { id: 28,  icon: "ion-sync-pivotgrid", control: "PivotGrid", name: "PivotGrid" },
		  { id: 29,  icon: "ion-sync-pivottreemap", control: "PivotTreeMap", name: "PivotTreeMap" },
          { id: 30,  icon: "ion-sync-progressbar", control: "Progressbar", name: "Progressbar" },
          { id: 31,  icon: "ion-sync-radialmenu", control: "RadialMenu", name: "RadialMenu" },
          { id: 32,  icon: "ion-sync-radialslider", control: "RadialSlider", name: "RadialSlider" },
          { id: 33,  icon: "ion-sync-rangenavigator", control: "RangeNavigator", name: "RangeNavigator" },
          { id: 34,  icon: "ion-sync-rating", control: "Rating", name: "Rating" },
          { id: 36,  icon: "ion-sync-ribbon", control: "Ribbon", name: "Ribbon" },
          { id: 37,  icon: "ion-sync-rotator", control: "Rotator", name: "Rotator" },
          { id: 38,  icon: "ion-sync-rte", control: "RTE", name: "RTE" },
          { id: 39,  icon: "ion-sync-schedule", control: "Schedule", name: "Schedule" },
          { id: 40,  icon: "ion-sync-scroller", control: "Scrollbar", name: "Scrollbar" },
          { id: 41,  icon: "ion-sync-signature", control: "Signature", name: "Signature" },		  
          { id: 42,  icon: "ion-sync-slider", control: "Slider", name: "Slider" },
          { id: 43,  icon: "ion-sync-sparkline", control: "Sparkline", name: "Sparkline" },
          { id: 44,  icon: "ion-sync-splitter", control: "Splitter", name: "Splitter" },
          { id: 45,  icon: "ion-sync-spreadsheet", control: "Spreadsheet", name: "Spreadsheet" },
		  { id: 57,  icon: "ion-sync-sunburst", control: "Sunburst Chart", name: "Sunburst" },
          { id: 46,  icon: "ion-sync-tab", control: "Tab", name: "Tab" },
          { id: 47,  icon: "ion-sync-tagcloud", control: "TagCloud", name: "TagCloud" },
          { id: 48,  icon: "ion-sync-textboxes", control: "Textboxes", name: "Textboxes" },
          { id: 49,  icon: "ion-sync-tileview", control: "TileView", name: "TileView" },
          { id: 50,  icon: "ion-sync-timepicker", control: "TimePicker", name: "TimePicker" },
          { id: 51,  icon: "ion-sync-toolbar", control: "Toolbar", name: "Toolbar" },
        // { id: 51,  icon: "ion-sync-tooltip", control: "Tooltip", name: "Tooltip" },
          { id: 52,  icon: "ion-sync-treegrid", control: "TreeGrid", name: "TreeGrid" },
          { id: 53,  icon: "ion-sync-treemap", control: "TreeMap", name: "TreeMap" },
          { id: 54,  icon: "ion-sync-treeview", control: "TreeView", name: "TreeView" },
          { id: 55,  icon: "ion-sync-uploadbox", control: "Uploadbox", name: "Uploadbox" },
          { id: 56,  icon: "ion-sync-waitingpopup", control: "WaitingPopUp", name: "WaitingPopUp" },
          { id: 57,  icon: "ion-sync-spellcheck", control: "SpellCheck", name: "SpellCheck" }]

window.controlFields = {
    "text": "control",
    "imageClass":"icon",
    "id": "id",
    "attributes":"name"
};

var searchFields= { 
	text: "control"
};